const datosMemoria = [
    {
        lat: -34.7965, lng: -58.2838,
        nombre: "ACOSTA SELFO, Ramón Gumersindo Manuel (34 años)",
        apodo: "Juan Carlos Gómez",
        fecha: "21/02/1976",
        dni: "5.939.386",
        nacionalidad:"Argentino",
        lugar: "El Cadillal, Tafí Viejo, Tucumán. Zona 3, Subzona 32, Área 321",
        profesion: "Obrero portuario, Delegado Gremial Ferrodúctil (Metalúrgico)",
        historia:"Partido Revolucionario de los Trabajadores-Ejército Revolucionario del Pueblo PRT-ERP",
        imagen: "images/ACOSTA-SELFO.png"
    },
    {
        lat: -34.7940, lng: -58.2800,
        nombre: "ACUÑA RAMOS MEJÍA, Federico Matías Ramón (26 años)",
        apodo: "Damián Barrios",
        fecha: "00/03/1977",
        dni: "8.474.425",
        nacionalidad:"Argentino",
        lugar: "Capital Federal. Zona 1, Subzona Capital Federal, Área 1. Operativo en una fábrica. Militaba en Florencio Varela.",
        profesion: "Sin datos",
        historia:"CCD:EL BANCO / PUENTE 12\nOperativo en una fábrica. Sobrino de José Alfredo Martínez de Hoz. Militaba en Florencio Varela",
        imagen: "images/ACUÑA-RAMOS-MEJÍA.png"
    },
    {
        lat: -34.7910, lng: -58.2770,
        nombre: "ACUÑA, Néstor Porfirio (27 años)",
        apodo: "Falucho",
        fecha: "25/01/1978",
        dni: "Sin datos",
        nacionalidad:"Sin datos",
        lugar: "Plaza Constitución. Zona 1, Subzona Capital Federal.",
        profesion: "Obrero textil. Partido Comunista Marxista-Leninista.",
        ccd: "El Banco",
        historia: "Domicilio: López Escribano 1114, Florencio Varela\n CCD:EL BANCO\nPartido Comunista Marxista-Leninista",
        imagen: ""
    },
    {
        lat: -34.7550, lng: -58.2100,
        nombre: "ACUÑA BRIZUELA, Teodosio (21 años)",
        apodo: "Gordo Hugo / Toto",
        fecha: "15/04/1976",
        dni: "Sin datos",
        nacionalidad:"Argentino",
        lugar: "Ramos Mejía. Zona 1, Subzona 11, Área 116",
        profesion: "Obrero frigorífico Subpga",
        ccd: "El Banco",
        historia: "CCD: EL BANCO\nPartido Comunista Marxista-Leninista\nEs detenido en una pensión de Ramos Mejía y en su Legajo SDH figura que fue detenido entre el trayecto de su trabajo (Camino General Belgrano Km. 21.500. Berazategui) a su casa",
        imagen: ""
    },
    {
        lat: -34.8020, lng: -58.2750,
        nombre: "ALBORNOZ GARCÍA, Mario Raúl (24 años)",
        apodo: "Sin datos",
        fecha: "25/07/1975 (Ejecución Sumaria)",
        dni: "8.575.579",
        nacionalidad:"Argentino",
        lugar: "Monseñor Aragón entre Estados Unidos y Agrelo, Barrio La Pileta, Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Sin datos",
        historia: "Partido Revolucionario de los Trabajadores-Ejército Revolucionario del Pueblo PRT-ERP",
        imagen: ""
    },
    {
        lat: -34.7780, lng: -58.2580,
        nombre: "ALTAMIRANDA ROJAS, Horacio Antonio (22 años)",
        apodo: "Gallego Marcelo / Roberto",
        fecha: "13/05/1977",
        dni: "11.886.638",
        nacionalidad:"Argentino",
        lugar: "Perú y P. Elía s/n, Ingeniero Allan, Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Delegado gremial de Rigolleau",
        historia: "CCD: EL VESUBIO\nPartido Revolucionario de los Trabajadores-Ejército Revolucionario del Pueblo PRT-ERP",
        imagen: "images/ALTAMIRANDA-ROJAS.png"
    },
    {
        lat: -34.7950, lng: -58.2820,
        nombre: "ARDETI MOLARO, Enrique Néstor (44 años)",
        apodo: "Gordo Ramón",
        fecha: "06/08/1979",
        dni: "6.222.896",
        nacionalidad:"Argentino",
        lugar: "Avenida Vázquez 375, Florencio Varela, a las 17:20 horas. Zona 1, Subzona 11, Área 116.",
        profesion: "Sin datos",
        historia: "Domicilio: Calle 46 Nº 1827, La Plata.\nNro. de legajo: 2516\nFuerzas Armadas Peronistas FAP- Peronismo de Base PB\nCCD: ESCUELA DE MECANICA DE LA ARMADA",
        imagen: "images/ARDETI-MOLARO.png"
    },
    {
        lat: -34.7680, lng: -58.2350,
        nombre: "ASCONAPE LUAYZA, María Cristina (24 años)",
        apodo: "Sin datos",
        fecha: "12/09/1975 (Ejecución Sumaria)",
        dni: "6.553.297",
        nacionalidad:"Argentina",
        lugar: "Alelíes esquina Las Orquídeas, Bosques, Ruta 2 Km 28.800, Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Ayudante de radiología. PRT-ERP.",
        historia: "Partido Revolucionario de los Trabajadores-Ejército Revolucionario del Pueblo PRT-ERP",
        imagen: "images/ASCONAPE-LUAYZA.png"
    },
    {
        lat: -34.7990, lng: -58.2870,
        nombre: "BARBEITO RODRÍGUEZ, María Cristina (22 años)",
        apodo: "Sin datos",
        fecha: "17/10/1977 (Asesinada)",
        dni: "11.741.547",
        nacionalidad:"Argentina",
        lugar: "Chubut y Jujuy, Florencio Varela. Zona 1, Subzona 11, Área 116. Compañera de Juan Carlos Follonier. Es asesinada en Varela poniendo a reparo su hijo y cubriendo a Víctor Hugo Díaz.",
        profesion: "Estudiante",
        historia: "REDEFA 116\nMontoneros. Compañera de Juan Carlos Follonier. Es asesinada en Varela poniendo a reparo su hijo y cubriendo a Víctor Hugo Díaz",
        imagen: "images/BARBEITO-RODRÍGUEZ.png"
    },
    {
        lat: -34.7900, lng: -58.2760,
        nombre: "BARTUCCI DEMASI, Francisco (29 años)",
        apodo: "Pancho",
        fecha: "29/07/1976",
        dni: "CI: 9.744.456",
        nacionalidad:"Italiano",
        lugar: "Curva de Berraymundo, Florencio Varela, a las 17 horas. Zona 1, Subzona 11, Área 116.",
        profesion: "Obrero de SEGBA.",
        historia: "Domicilio: Luis Villar 664, Florencio Varela.\nNro. de legajo: 4329\nMontoneros",
        imagen: "images/BARTUCCI-DEMASI.png"
    },
    {
        lat: -34.7935, lng: -58.2810,
        nombre: "BELIZÁN, Eusebio (40 años)",
        apodo: "Sin datos",
        fecha: "15/02/1971",
        dni: "7.152.984",
        nacionalidad: "Argentino",
        lugar: "Se ignora / no consta. Zona 1, Subzona 11, Área 116.",
        profesion: "Obrero",
        historia: "Domicilio: Florencio Varela.\nNro. de legajo: 1055",
        imagen: ""
    },
    {
        lat: -34.7320, lng: -58.2460,
        nombre: "BARRY, Enrique Rodolfo",
        apodo: "Pingüino",
        fecha: "22/10/1976",
        dni: "LE: 7.793.394",
        nacionalidad: "Argentino",
        lugar: "Bernal, Quilmes. Zona 1, Subzona 11, Área 111. Secuestrado en calle Montevideo entre Calchaquí y Dardo Rocha en Bernal, entre las 18 y las 20 horas.",
        profesion: "Empleado en fabrica de ropa",
        historia: "Montoneros (responsable de sector Montoneros donde militaba Mirta Gerelli). Vivía en la calle Brasil (ex 402) entre E. del Campo (ex 493) y Caseros (ex 492), Villa La Florida, Ezpeleta Oeste, Quilmes. Trabajaba en una fábrica que confeccionaba ropa de trabajo. Su compañera era Luján Susana Papic.",
        imagen: "images/BARRY-ENRIQUE.png"
    },
    {
        lat: -34.8010, lng: -58.2780,
        nombre: "BENITEZ ACUÑA, Antonio Esteban (33 años)",
        apodo: "Sin datos",
        fecha: "02/05/1976 (Ejecución Sumaria)",
        dni: "Sin datos",
        nacionalidad: "Argentino",
        lugar: "General Conesa y General Rodríguez, Estanislao Severo Zeballos, Florencio Varela. Zona 1, Subzona 11, Área 111.",
        profesion: "Sin datos",
        historia: "",
        imagen: ""
    },
    {
        lat: -34.7870, lng: -58.2730,
        nombre: "BRUNO MAGNANI, Marcos Pedro (57 años)",
        apodo: "Sin datos",
        fecha: "11/02/1977",
        dni: "394.540",
        nacionalidad: "Argentino",
        lugar: "Calle 17 s/n, Barrio Libertad, Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Desocupado. Sereno en una fábrica (Camino General Belgrano y Cadorna)",
        historia: "Partido Justicialista",
        imagen: "images/BRUNO-MAGNANI.png"
    },
    {
        lat: -34.7710, lng: -58.2640,
        nombre: "BUSANICHE, Graciela María (29 años)",
        apodo: "Juana / Color / Colorada",
        fecha: "09/09/1977",
        dni: "Sin datos",
        nacionalidad: "Argentina",
        lugar: "Rosario. Zona 2, Subzona 21, Área 211.",
        profesion: "Trabajadora social. Docente en la Facultad de Trabajo Social de la Universidad Nacional de Rosario",
        historia: "Montoneros. Militó durante un tiempo en el grupo de Villa del Plata.",
        imagen: "images/BUSANICHE.png"
    },
    {
        lat: -34.7960, lng: -58.2850,
        nombre: "CANO, Rosa María (32 años)",
        apodo: "Marta",
        fecha: "06/04/1977",
        dni: "LC: 4.791.252",
        nacionalidad: "Argentina",
        lugar: "Arenales 1275, 6º piso, departamento 12, Retiro, Capital Federal. Zona 1, Subzona Capital Federal, Área 1.",
        profesion: "Sin datos",
        historia: "SDH 2959\nMontoneros. Pareja de Federico Matías Ramón Acuña Ramos Mejía. Militaba en Florencio Varela. Hizo tareas de alfabetización en Florencio Varela donde también militaba y luego pasó a Quilmes, siempre en la zona sur del Gran Buenos Aires.",
        imagen: "images/CANO.png"
    },
    {
        lat: -34.7720, lng: -58.2400,
        nombre: "CARBALLO GELPI, José Alberto (20 años)",
        apodo: "Aníbal / Negro Antonio",
        fecha: "03/06/1976",
        dni: "12.926.511",
        nacionalidad: "Argentino",
        lugar: "Rotonda de Acassuso, San Isidro. Zona 4, Área 420.",
        profesion: "Cervecería Quilmes. UES–Montoneros",
        historia: "Domicilio: Riobamba y Hernandarias Nº 181, Bosques, Florencio Varela.\nResponsable de la UES de la Columna Sur y responsable de la UES Columna Norte.\nCCD: Escuela de Mecánica de la Armada",
        imagen: "images/CARBALLO-GELPI.png"
    },
    {
        lat: -34.7985, lng: -58.2690,
        nombre: "CARO de SOUTO, Marta Susana (24 años)",
        apodo: "La Negrita",
        fecha: "01/05/1976",
        dni: "10.156.131",
        nacionalidad: "Argentina",
        lugar: "Santa Adela entre Soler y Hudson, Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Obrera de Alpargatas",
        historia: "Domicilio: Bahía Blanca 462, Florencio Varela.\nPartido Revolucionario de los Trabajadores-Ejército Revolucionario del Pueblo PRT-ERP",
        imagen: "images/CARO-DESOUTO.png"
    },
    {
        lat: -34.8005, lng: -58.2745,
        nombre: "CORREA ALCARAZ, Ramón Beato (18 años)",
        apodo: "Sin datos",
        fecha: "26/07/1975",
        dni: "Sin datos",
        nacionalidad: "Argentino",
        lugar: "Monseñor Aragón entre Estados Unidos y Agrelo, Barrio La Pileta, Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Jornalero",
        historia: "Nro. de legajo: 3418",
        imagen: ""
    },
    {
        lat: -34.7855, lng: -58.2615,
        nombre: "CORREA VIERA, Ramón Jorge (22 años)",
        apodo: "Sin datos",
        fecha: "12/04/1975",
        dni: "Sin datos",
        nacionalidad: "Argentino",
        lugar: "Santa Ana, Tucumán. Zona 3, Subzona 32, Área 321.",
        profesion: "Sin datos",
        historia: "Domicilio: Matienzo 420 (actual Castelli) entre Argerich y Mayor Olivera, Barrio Chacabuco, Florencio Varela.\nPartido Revolucionario de los Trabajadores-Ejército Revolucionario del Pueblo PRT-ERP",
        imagen: "images/CORREA-VIERA.png"
    },
    {
        lat: -34.7845, lng: -58.2680,
        nombre: "CORSIGLIA DANIELE, Hugo Arnaldo (27 años)",
        apodo: "Sin datos",
        fecha: "10/08/1977",
        dni: "8.309.507",
        nacionalidad: "Argentino",
        lugar: "Gorriti 1365, Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Estudiante de Arquitectura UNLP. Dibujante",
        historia: "Nro. de legajo: 3418\nOrganización Comunista Poder Obrero (OCPO), se había unificado a principios de mayo de 1977 con las Fuerzas Armadas de Liberación \"22 de Agosto\".\nCCD: Escuela de Mecánica de la Armada",
        imagen: "images/CORSIGLIA-DANIELE.png"
    },
    {
        lat: -34.7920, lng: -58.2795,
        nombre: "DE MAESTRI CORBELLA, Daniel Luis (26 años)",
        apodo: "Sin datos",
        fecha: "08/02/1977",
        dni: "LE: 8.366.695",
        nacionalidad: "Argentino",
        lugar: "Contreras 272, Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Estudiante de Medicina",
        historia: "Nro. de legajo: 1838\nMontoneros. Trabajaba ad honorem en una sala de primeros auxilios del barrio El Ombú de Florencio Varela acondicionada para curar a personas de bajos recursos económicos.",
        imagen: "images/DE-MAESTRI-CORBELLA.png"
    },
    {
        lat: -34.7975, lng: -58.2720,
        nombre: "DE OLIVERA, Juan Ricardo (30 años)",
        apodo: "Sin datos",
        fecha: "12/08/1974",
        dni: "LE: 7.585.092",
        nacionalidad: "Argentino",
        lugar: "Piedra Blanca, Fray Mamerto Esquiú, Catamarca. Zona 1, Subzona 31.",
        profesion: "Estudiante de Medicina",
        historia: "SDH 3863\nDomicilio: Florencio Varela.\nPartido Revolucionario de los Trabajadores-Ejército Revolucionario del Pueblo PRT-ERP. Participa en Tucumán desde julio de 1974.",
        imagen: ""
    },
    {
        lat: -34.7890, lng: -58.2650,
        nombre: "DI SPALATRO BURGOS, Mario Alberto",
        apodo: "Sin datos",
        fecha: "14/02/1977",
        dni: "Sin datos",
        nacionalidad: "Argentino",
        lugar: "Terminal Línea 300, Berazategui. Zona 1, Subzona 11, Área 116.",
        profesion: "Trabajaba en la Municipalidad de Florencio Varela. Estudiante de Psicología y Medicina en la UNLP. Talleres de teatro",
        historia: "Nro. de legajo: 1526\nPartido Socialista de los Trabajadores (PST)",
        imagen: "images/DI-SPALATRO-BURGOS.png"
    },
    {
        lat: -34.7960, lng: -58.2830,
        nombre: "D'ONOFRIO IBERN, Rosana Victoria (20 años)",
        apodo: "Sin datos",
        fecha: "17/10/1976",
        dni: "LC: 12.026.059",
        nacionalidad: "Argentina",
        lugar: "Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Trabajaba en la fábrica FIFA, subsidiaria de AGFA, Florencio Varela",
        historia: "CONADEP 4385\nMontoneros",
        imagen: ""
    },
    {
        lat: -34.8000, lng: -58.2770,
        nombre: "ECHAVARRÍA ZORNADA, Graciela Ángela (20 años)",
        apodo: "Sin datos",
        fecha: "04/05/1976",
        dni: "CI: 7.816.986",
        nacionalidad: "Argentina",
        lugar: "San Nicolás 2569, Estanislao Zeballos, Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Obrera de Alpargatas",
        historia: "Partido Revolucionario de los Trabajadores-Ejército Revolucionario del Pueblo PRT-ERP. Embarazada de 2 o 3 meses.",
        imagen: "images/ECHAVARRÍA-ZORNADA.png"
    },
    {
        lat: -34.7880, lng: -58.2710,
        nombre: "FLORES BUHLER, José Andrés (19 años)",
        apodo: "Sin datos",
        fecha: "01/02/1977 (Ejecución sumaria el 08/03/1977)",
        dni: "13.634.302",
        nacionalidad: "Argentino",
        lugar: "Sargento Cabral e Independencia, Florencio Varela. Zona 1, Subzona 11, Área 112.",
        profesion: "Sin datos",
        historia: "REDEFA: 6736\nFecha de asesinato: 08/03/1977. Lugar de asesinato: Almirante Brown.",
        imagen: ""
    },
    {
        lat: -34.7830, lng: -58.2590,
        nombre: "FOLLONIER BERNI, Adrián Omar (24 años)",
        apodo: "Manolo / Juan Bautista",
        fecha: "30/04/1978",
        dni: "11.168.079 / CI: 8.127.998",
        nacionalidad: "Argentino",
        lugar: "San Pedro. Zona 1, Subzona 13, Área 132.",
        profesion: "Sin datos",
        historia: "CONADEP: 4199\nDomicilio: Ruta 2 y Antártida Argentina, Florencio Varela.\nJuventud Peronista – Montoneros",
        imagen: "images/FOLLONIER-BERNI.png"
    },
    {
        lat: -34.7915, lng: -58.2750,
        nombre: "GALVÁN, Julio Alberto (18 años)",
        apodo: "Sin datos",
        fecha: "01/02/1977 (Ejecución sumaria el 08/03/1977)",
        dni: "13.634.302",
        nacionalidad: "Argentino",
        lugar: "Cuyo y Juan XXIII, Florencio Varela. Zona 1, Subzona 11, Área 112.",
        profesion: "Changarín",
        historia: "REDEFA: 6736\nFecha de asesinato: 08/03/1977. Lugar de asesinato: Almirante Brown.",
        imagen: ""
    },
    {
        lat: -34.7945, lng: -58.2860,
        nombre: "GÁNDARA CASTROMÁN, Elba Lucía (33 años)",
        apodo: "Sin datos",
        fecha: "18/02/1977",
        dni: "CI: 1.130.306",
        nacionalidad: "Uruguaya",
        lugar: "Hilario Lagos 466, Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Sin datos",
        historia: "CONADEP: 2628\nCCD: Departamento Central de Policía de la Provincia de Buenos Aires (Jefatura La Plata), Regimiento de Infantería 3 Mecanizado \"General Belgrano\", La Tablada, Puente 12, El Banco.",
        imagen: "images/GÁNDARA-CASTROMÁN.png"
    },
    {
        lat: -34.7925, lng: -58.2740,
        nombre: "GARAY PRESENTADO, Avelino Enrique (27 años)",
        apodo: "Quique",
        fecha: "14/09/1976",
        dni: "LE: 7.802.166",
        nacionalidad: "Argentino",
        lugar: "Aristóbulo del Valle 359, Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Obrero mecánico",
        historia: "CONADEP: 1289\nPartido Comunista",
        imagen: "images/GARAY-PRESENTADO.png"
    },
    {
        lat: -34.7340, lng: -58.2480,
        nombre: "GERELLI, Mirta Teresa",
        apodo: "Sin datos",
        fecha: "26/02/1977",
        dni: "Sin datos",
        nacionalidad: "Argentina",
        lugar: "Quilmes. Zona 1, Subzona 11, Área 111.",
        profesion: "Docente, estudiante de Plástica en la UNLP",
        historia: "CONADEP: 4343\nMontoneros. Vinculada al ámbito de Enrique \"Pingüino\" Barry. Ámbito de militancia en la zona de Mármol y Rafael Calzada. Separada, forma pareja con Carlos Esteban \"Chamaco\" Rodríguez, cuadro de Juventud Peronista y Montoneros, militaba en una Unidad Básica de Remedios de Escalada. Fue secuestrado-desaparecido en la estación de trenes de Quilmes el 26 de febrero de 1977 a la edad de 23 años. Mirta fue vista en el CCD Pozo de Quilmes antes de su asesinato.",
        imagen: "images/GERELLI.png"
    },
    {
        lat: -34.7955, lng: -58.2815,
        nombre: "GIMÉNEZ, Mario César (20 años)",
        apodo: "Sin datos",
        fecha: "04/08/1976",
        dni: "92.088.454",
        nacionalidad: "Paraguayo",
        lugar: "Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Curtidor operario, delegado sindical en Beeca. Trabajaba en Palamades S.A., empresa constructora",
        historia: "CONADEP: 5365\nJuventud Peronista. Visto en comisaría de Florencio Varela el 27/08/1976.\nCCD: Los Plátanos y Pozo de Quilmes.\nNacido el 30 de diciembre de 1955. La primaria la realizó en Paraguay y la secundaria en Wilde, provincia de Buenos Aires.",
        imagen: "images/GIMÉNEZ.png"
    },
    {
        lat: -34.7870, lng: -58.2670,
        nombre: "GODOY RUIZ, José Luis (21 años)",
        apodo: "Bicho",
        fecha: "04/1978",
        dni: "12.445.050 / CI: 9.136.079",
        nacionalidad: "Argentino",
        lugar: "San Francisco Solano. Zona 1, Subzona 11, Área 111.",
        profesion: "Sin datos",
        historia: "SDH: 3165\nNacido en Florencio Varela el 13/09/1956.\nMontoneros",
        imagen: ""
    },
    {
        lat: -34.7940, lng: -58.2790,
        nombre: "GODOY RUIZ, Orlando Rubén",
        apodo: "Pita Andresito",
        fecha: "22/03/1977",
        dni: "11.439.786 / CI: 8.583.865",
        nacionalidad: "Argentino",
        lugar: "Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Empleado frigorífico de Carindú en Quilmes",
        historia: "SDH: 3164\nDomicilio: Barrio La Sirena.\nNacido en Florencio Varela el 07/01/1955.\nMontoneros",
        imagen: ""
    },
    {
        lat: -34.7895, lng: -58.2735,
        nombre: "GÓMEZ, Juan Carlos (22 años)",
        apodo: "Sin datos",
        fecha: "04/05/1976",
        dni: "10.739.431",
        nacionalidad: "Argentino",
        lugar: "Calle Nº 17 entre 2 y 3, Barrio El Parque, Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Obrero de frigorífico Subpga",
        historia: "SDH: 3748\nCCD: Regimiento de Infantería 7, La Plata",
        imagen: ""
    },
    {
        lat: -34.7980, lng: -58.2850,
        nombre: "GÓMEZ, Marcos Marcelino (30 años)",
        apodo: "Sin datos",
        fecha: "03/09/1976",
        dni: "5.674.892",
        nacionalidad: "Argentino",
        lugar: "Nuestras Malvinas 1249, Barrio La Sirena, Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Obrero de Bagley, sección limpieza, delegado de sección",
        historia: "SDH: 590",
        imagen: ""
    },
    {
        lat: -34.7860, lng: -58.2695,
        nombre: "GÓMEZ MAIDANA, Valerio (33 años)",
        apodo: "Sin datos",
        fecha: "04/04/1980",
        dni: "Sin datos",
        nacionalidad: "Argentino",
        lugar: "Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Sin datos",
        historia: "SDH: 939",
        imagen: ""
    },
    {
        lat: -34.7910, lng: -58.2760,
        nombre: "GÓMEZ, Rodolfo Héctor (22 años)",
        apodo: "Sin datos",
        fecha: "24/01/1978",
        dni: "LE: 11.886.202",
        nacionalidad: "Argentino",
        lugar: "Calle Gorriti, Barrio Martín Fierro, Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Sin datos",
        historia: "",
        imagen: ""
    },
    {
        lat: -34.7935, lng: -58.2805,
        nombre: "GÓMEZ SANTANA, Mónica Graciela (17 años)",
        apodo: "Sin datos",
        fecha: "13/06/1978",
        dni: "CI: 3.626.239",
        nacionalidad: "Argentina",
        lugar: "Trayecto entre la estación Florencio Varela del Ferrocarril Roca y la casa de una amiga. Zona 1, Subzona 11, Área 116.",
        profesion: "Estudiante secundaria. Empleada de comercio en Capital Federal",
        historia: "CONADEP: 3620\nDomicilio: Villegas 39, Barrio Villa Vatteone, Florencio Varela.",
        imagen: "images/GÓMEZ-SANTANA.png"
    },
    {
        lat: -34.7950, lng: -58.2830,
        nombre: "GÓMEZ SUÁREZ, Juan Carlos (22 años)",
        apodo: "Sin datos",
        fecha: "04/05/1976",
        dni: "DNI: 10.739.431",
        nacionalidad: "Argentina",
        lugar: "Domicilio: Calle 17 entre 2 y 3, Barrio Parque, Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Sin datos",
        historia: "SDH: 3748",
        imagen: ""
    },
    {
        lat: -34.7870, lng: -58.2680,
        nombre: "GONZÁLEZ SALOMÉ, Rubén Amaro (20 años)",
        apodo: "Sin datos",
        fecha: "30/12/1976",
        dni: "DNI: 12.052.347",
        nacionalidad: "Argentina",
        lugar: "Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Obrero vidriero en Cristalux, Avellaneda",
        historia: "CONADEP: 2788\nDomicilio: Quilmes.\nIdentificado por resolución de la Justicia Federal.",
        imagen: "images/GONZÁLEZ-SALOMÉ.png"
    },
    {
        lat: -34.7990, lng: -58.2720,
        nombre: "GORDILLO, Marcela María (26 años)",
        apodo: "LA FLACA MARÍA",
        fecha: "20/10/1976",
        dni: "DNI: 10.662.006",
        nacionalidad: "Argentina",
        lugar: "Morón. Zona 1, Subzona 16, Área 161.",
        profesion: "Militante peronista y montonera",
        historia: "CONADEP: 2032\nMontoneros. Fue vista en la Escuela de Mecánica de la Armada (ESMA). Militaba en el grupo de Villa del Plata, Florencio Varela. Compañera de César Vela. Vivía con César Vela y su hijo de dos años.\nSecuestrada por un grupo de tareas de la Armada en Morón, provincia de Buenos Aires, el 20 de octubre de 1976. Una vez en la ESMA consiguió tomar una pastilla de cianuro que tenía escondida consigo, autoeliminándose y consiguiendo una última victoria, pírrica, sobre sus captores.",
        imagen: ""
    },
    {
        lat: -34.7845, lng: -58.2650,
        nombre: "GUSHIKEN ARASAKI, Carlos Horacio (21 años)",
        apodo: "MONO JAPO",
        fecha: "08/04/1978",
        dni: "DNI: 12.443.147 / CI: 87752",
        nacionalidad: "Argentino",
        lugar: "Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Operario en Cristalería Rigolleau (Berazategui). Partido Comunista Marxista-Leninista",
        historia: "CONADEP: 1612\nREDEFA: 6803\nFecha de asesinato: 13/07/1978. Lugar de asesinato: Paraje Barranca de los Lobos, Mar del Plata, Gral. Pueyrredón.\nEn julio de 2003 fueron exhumados e identificados sus restos por el EAAF (intervención de la Cámara Federal).",
        imagen: "images/GUSHIKEN-ARASAKI.png"
    },
    {
        lat: -34.7860, lng: -58.2590,
        nombre: "GUSHIKEN KISHIMOTO, Julio Eduardo (20 años)",
        apodo: "JAPO",
        fecha: "00/06/1976",
        dni: "DNI: 12.443.149 / CI: 3.049.330",
        nacionalidad: "Argentino, nacido en Florencio Varela",
        lugar: "Capital Federal. Zona 1, Subzona Capital Federal.",
        profesion: "Obrero textil. Partido Comunista Marxista-Leninista",
        historia: "CONADEP: 0452",
        imagen: "images/GUSHIKEN-KISHIMOTO.png"
    },
    {
        lat: -34.8010, lng: -58.2780,
        nombre: "HLACZIK de POBLETE, Gertrudis María",
        apodo: "LUCY",
        fecha: "28/11/1978",
        dni: "Sin datos",
        nacionalidad: "Sin datos",
        lugar: "Guernica. Zona 1, Subzona 11, Área 113.",
        profesion: "Estudiante de Psicología",
        historia: "CONADEP: 3685\nCCD: Olimpo.\nSecuestrada con su hija Claudia Victoria, de 8 meses, y su marido Poblete Roa José Liborio, lisiado, tenía las dos piernas amputadas. Fue vista en el Olimpo por Ghezan, Caride, Lombardo.",
        imagen: "images/HLACZIK-DE-POBLETE.png"
    },
    {
        lat: -34.7920, lng: -58.2640,
        nombre: "INSAURRALDE DOMÍNGUEZ, Pedro Roberto (30 años)",
        apodo: "Sin datos",
        fecha: "12/02/1977",
        dni: "LE: 8.228.599",
        nacionalidad: "Argentino",
        lugar: "Camino General Belgrano, Florencio Varela. Zona 1, Subzona Capital Federal.",
        profesion: "Músico",
        historia: "CONADEP: 7511",
        imagen: "images/INSAURRALDE-DOMÍNGUEZ.png"
    },
    {
        lat: -34.7975, lng: -58.2710,
        nombre: "IULA, Ángel Alberto (21 años)",
        apodo: "EL CABEZÓN",
        fecha: "26/05/1978",
        dni: "LE: 12.926.616",
        nacionalidad: "Argentino",
        lugar: "Ramos Mejía. Zona 1, Subzona 11, Área 114.",
        profesion: "Estudiante. Empleado. Partido Comunista Marxista-Leninista",
        historia: "CONADEP: 4121\nCCD: El Banco.",
        imagen: "images/IULA.png"
    },
    {
        lat: -34.7895, lng: -58.2750,
        nombre: "JIMÉNEZ MARTÍNEZ, Domingo Orlando (19 años)",
        apodo: "Sin datos",
        fecha: "09/11/1977",
        dni: "Sin datos",
        nacionalidad: "Argentino",
        lugar: "Comisaría de Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Obrero de Cervecería Quilmes",
        historia: "CONADEP: 2410\nDomicilio: Manuel Iglesias Nº 683, Bº Villa Mónica, Florencio Varela.",
        imagen: "images/JIMÉNEZ-MARTÍNEZ.png"
    },
    {
        lat: -34.7940, lng: -58.2670,
        nombre: "KLOSOWSKI, Héctor Daniel",
        apodo: "Sin datos",
        fecha: "02/02/1977",
        dni: "DNI: 10.413.724",
        nacionalidad: "Argentina",
        lugar: "Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Sin datos",
        historia: "CONADEP: 5306",
        imagen: ""
    },
    {
        lat: -34.7855, lng: -58.2620,
        nombre: "LEBED, María Susana (24 años)",
        apodo: "Sin datos",
        fecha: "30/09/1976",
        dni: "LC: 6.689.705",
        nacionalidad: "Argentina",
        lugar: "Calle 12 Nº 1180 entre 17 y 19, City Bell. Zona 1, Subzona 11, Área 114.",
        profesion: "Profesora de francés. Médica residente en el Hospital Municipal de Florencio Varela",
        historia: "CONADEP: 3581\nDomicilio: Calle 12 Nº 1180, City Bell.\nJUP-Montoneros. Allí mantenía fuertes enfrentamientos con el jefe de la guardia.",
        imagen: "images/LEBED.png"
    },
    {
        lat: -34.7980, lng: -58.2590,
        nombre: "LÉPORE, José Antonio",
        apodo: "TANO",
        fecha: "26/05/1978",
        dni: "DNI: 12.926.376",
        nacionalidad: "Argentino",
        lugar: "Calle Buenviaje y 9 de Julio, Ramos Mejía. Zona 1, Subzona 11, Área 114.",
        profesion: "Empresa de Transportes Ben-Hur, Cap. Federal. Partido Comunista Marxista-Leninista",
        historia: "CONADEP: 5096\nDomicilio: Monteagudo Nº 800, Florencio Varela.",
        imagen: "images/LÉPORE.png"
    },
    {
        lat: -34.7910, lng: -58.2700,
        nombre: "LOGIURATO ÁLVAREZ, Luis María (38 años)",
        apodo: "Sin datos",
        fecha: "13/06/1977",
        dni: "DNI: 5.172.983",
        nacionalidad: "Argentino",
        lugar: "Doblas Nº 1083, Parque Chacabuco, Capital Federal (domicilio de familiar). Zona 1, Subzona 11, Área 114.",
        profesion: "Comerciante. PROA (Partido Revolucionario Obrero Argentino)",
        historia: "CONADEP: 8344\nDomicilio: Florencio Varela.",
        imagen: "images/LOGIURATO-ÁLVAREZ.png"
    },
    {
        lat: -34.7865, lng: -58.2740,
        nombre: "LUCERO LAVALLÉN, Lady Noemí (38 años)",
        apodo: "Sin datos",
        fecha: "13/06/1976",
        dni: "DNI: 6.471.853",
        nacionalidad: "Argentina",
        lugar: "Florencio Varela. Zona 1, Subzona 11, Área 114.",
        profesion: "Ama de casa",
        historia: "CONADEP: 7660",
        imagen: ""
    },
    {
        lat: -34.7935, lng: -58.2660,
        nombre: "MEMMO MUSETTI, Claudio César (21 años)",
        apodo: "TORTUGA",
        fecha: "25/05/1978",
        dni: "LE: 11.419.402",
        nacionalidad: "Argentino",
        lugar: "Zona 1, Subzona 11, Área 114.",
        profesion: "Partido Comunista Marxista-Leninista",
        historia: "CONADEP: 8119\nDomicilio: Corrientes Nº 99, Florencio Varela.\nCCD: El Banco. Habría sido detenido en Ramos Mejía en una pensión junto con Acuña Teodocio.",
        imagen: "images/MEMMO-MUSETTI.png"
    },
    {
        lat: -34.7890, lng: -58.2810,
        nombre: "MOGENSEN REYES, Hugo Gustavo (22 años)",
        apodo: "EL GAUCHO",
        fecha: "12/09/1975",
        dni: "LE: 10.818.448",
        nacionalidad: "Argentino",
        lugar: "Alelíes y Las Orquídeas, Ruta Nacional Nº 2 Km 31.200, Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Estudiante de Sociología (UBA). Obrero Operario. PRT-ERP",
        historia: "REDEFA: 1602\nDomicilio: Alberdi 217/Uruguay 859, Berazategui.",
        imagen: ""
    },
    {
        lat: -34.7960, lng: -58.2770,
        nombre: "MOLINA, Buenaventura (54 años)",
        apodo: "Sin datos",
        fecha: "01/02/1976",
        dni: "DNI: 3.080.650",
        nacionalidad: "Argentino",
        lugar: "Sipe-Sipe y Pasco, Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Obrero independiente",
        historia: "CONADEP: 3151",
        imagen: ""
    },
    {
        lat: -34.7845, lng: -58.2690,
        nombre: "MONTOTO FERNÁNDEZ, Julio Tristán (22 años)",
        apodo: "Sin datos",
        fecha: "12/09/1975",
        dni: "LE: 10.617.177",
        nacionalidad: "Argentino",
        lugar: "Alelíes y Las Orquídeas, Ruta Nacional Nº 2 Km 31.200, Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Empleado. PRT-ERP",
        historia: "REDEFA: 326\nEjecución sumaria.",
        imagen: "images/MONTOTO FERNÁNDEZ.png"
    },
    {
        lat: -34.8005, lng: -58.2630,
        nombre: "MORALES, Ricardo Héctor",
        apodo: "Sin datos",
        fecha: "27/07/1975",
        dni: "Sin datos",
        nacionalidad: "Argentino",
        lugar: "Barrio Villa Aurora, Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Sin datos",
        historia: "Nro. de legajo: 0\nCausa Nº 24.965 –A– a disposición del PEN.",
        imagen: ""
    },
    {
        lat: -34.7915, lng: -58.2580,
        nombre: "MURA de CORSIGLIA, María Cristina (27 años)",
        apodo: "GORDA KIKA",
        fecha: "10/08/1977",
        dni: "LC: 6.237.209",
        nacionalidad: "Argentina",
        lugar: "Policía en Capital Federal (sin especificar). Zona 1, Subzona 11, Área 116.",
        profesion: "Médica Pediatra del Hospital Italiano. Consultorio en Riobamba 178 4º C, Capital Federal",
        historia: "CONADEP: 7207\nDomicilio: Gorriti Nº 1365, Florencio Varela.\nOrganización Comunista Poder Obrero. CCD: Escuela de Mecánica de la Armada.",
        imagen: "images/URA-DE-CORSIGLIA.png"
    },
    {
        lat: -34.7830, lng: -58.2720,
        nombre: "MUSSO, Pablo Daniel (25 años)",
        apodo: "Sin datos",
        fecha: "25/10/1976",
        dni: "LE: 6.647.398",
        nacionalidad: "Argentina",
        lugar: "Temperley. Zona 1, Subzona 11, Área 116.",
        profesion: "Técnico mecánico, trabajaba en la fábrica FIFA (subsidiaria de AGFA) Florencio Varela",
        historia: "CONADEP: 4345\nMontoneros. CCD: Brigada de Investigaciones de Lanús.",
        imagen: ""
    },
    {
        lat: -34.7905, lng: -58.2620,
        nombre: "OLDANI de REGGIARDO, Antonia (55 años)",
        apodo: "Sin datos",
        fecha: "08/02/1977",
        dni: "LC: 3.094.655",
        nacionalidad: "Argentina",
        lugar: "Monteagudo Nº 199, Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Ama de casa",
        historia: "CONADEP: 1833",
        imagen: ""
    },
    {
        lat: -34.7840, lng: -58.2560,
        nombre: "O'NEIL, Heber Eduardo (30 años)",
        apodo: "Sin datos",
        fecha: "18/01/1977",
        dni: "CI: 1.347.670",
        nacionalidad: "Uruguayo",
        lugar: "Estomba y Montenegro, Villa Ortúzar. Zona 1, Subzona Capital Federal, Área 1.",
        profesion: "Sin datos",
        historia: "CONADEP: 8362\nMilitante de Tupamaros en Uruguay y de JP-Montoneros en Argentina. Visto en CCD Pozo de Quilmes y El Vesubio.",
        imagen: ""
    },
    {
        lat: -34.7970, lng: -58.2680,
        nombre: "ORIETA LOREIRO, Miguel Ángel (25 años)",
        apodo: "Sin datos",
        fecha: "05/02/1977",
        dni: "LE: 8.571.332 / CI: 9.104.427",
        nacionalidad: "Argentino",
        lugar: "Zeballos, Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Obrero electricista",
        historia: "SDH: 2048\nCCD: La Tablada.",
        imagen: ""
    },
    {
        lat: -34.7885, lng: -58.2780,
        nombre: "PORTAS VÁZQUEZ, Osvaldo Horacio (27 años)",
        apodo: "INDIO",
        fecha: "15/08/1977",
        dni: "LE: 8.011.497",
        nacionalidad: "Argentina",
        lugar: "Lincoln y Bonifacini (imprenta), San Martín. Zona 1, Subzona 11, Área 116.",
        profesion: "Sin datos",
        historia: "SDH: 1550\nDomicilio: Gorriti 1365, Florencio Varela.\nO.C.P.O. / FAL 22 de Agosto.",
        imagen: ""
    },
    {
        lat: -34.7930, lng: -58.2600,
        nombre: "PAPIC, Luján Susana",
        apodo: "Sin datos",
        fecha: "22/10/1976",
        dni: "Sin datos",
        nacionalidad: "Argentina",
        lugar: "Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Secretaria de CTERA Adrogué",
        historia: "Montoneros.\nCompañera de Enrique Rodolfo 'Pingüino' Barry.",
        imagen: ""
    },
    {
        lat: -34.7850, lng: -58.2710,
        nombre: "PINTO RUBIO, María Angélica (21 años)",
        apodo: "Sin datos",
        fecha: "22/03/1977",
        dni: "CI: 7.310.780",
        nacionalidad: "Argentina (nacida en Chile)",
        lugar: "Lafinur y 384, Quilmes. Zona 1, Subzona 11, Área 116.",
        profesion: "Sin datos",
        historia: "CONADEP: 5267\nDomicilio: Barrio La Sirena, Florencio Varela.\nJuventud Peronista – Montoneros.",
        imagen: ""
    },
    {
        lat: -34.7995, lng: -58.2640,
        nombre: "POBLETE ROA, José Liborio",
        apodo: "Sin datos",
        fecha: "28/11/1978",
        dni: "Sin datos",
        nacionalidad: "Argentino",
        lugar: "Plaza Once. Zona 1, Subzona 11, Área 113.",
        profesion: "Sin datos",
        historia: "CONADEP: 3684\nDomicilio: Dorrego entre Las Heras y Falucho, Florencio Varela.\nCCD: El Olimpo.\nSecuestrado junto a su esposa Gertrudis María Hlaczik y su hija Claudia Victoria de 8 meses. Tenía ambas piernas amputadas.",
        imagen: ""
    },
    {
        lat: -34.7860, lng: -58.2750,
        nombre: "PINTOS, Leocadio de Jesús (44 años)",
        apodo: "Sin datos",
        fecha: "06/02/1977",
        dni: "LE: 6.987.235",
        nacionalidad: "Argentino",
        lugar: "Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Albañil",
        historia: "CONADEP: 5882",
        imagen: ""
    },
    {
        lat: -34.7865, lng: -58.2745,
        nombre: "PINTOS, Miguel Ángel (24 años)",
        apodo: "Sin datos",
        fecha: "06/02/1977",
        dni: "10.415.360",
        nacionalidad: "Argentino",
        lugar: "Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Ayudante de albañil",
        historia: "CONADEP: 5881",
        imagen: ""
    },
    {
        lat: -34.7875, lng: -58.2695,
        nombre: "QUIROGA, Jorge Alberto",
        apodo: "Sin datos",
        fecha: "03/03/1977",
        dni: "11.422.708",
        nacionalidad: "Argentino",
        lugar: "Cruce Varela, Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Comerciante",
        historia: "Montoneros. Visto en CCD Mansión Seré y CCD El Vesubio.",
        imagen: ""
    },
    {
        lat: -34.7920, lng: -58.2660,
        nombre: "REGGIARDO, Juan Enrique",
        apodo: "QUIQUE",
        fecha: "09/02/1977",
        dni: "10.641.616",
        nacionalidad: "Argentina",
        lugar: "Fábrica Hemigraf, Bouchard 1078, Lanús. Zona 1, Subzona 11, Área 112.",
        profesion: "Empleado gráfico",
        historia: "CONADEP: 1834\nDomicilio: Monteagudo 199, Florencio Varela.\nJuventud Peronista – Montoneros. CCD: La Cacha.",
        imagen: ""
    },
    {
        lat: -34.7950, lng: -58.2730,
        nombre: "RINALDI SARLO, Elena (26 años)",
        apodo: "Sin datos",
        fecha: "02/02/1977",
        dni: "LC: 6.528.393",
        nacionalidad: "Argentina",
        lugar: "Intendente Oliveri 536, Quilmes. Zona 1, Subzona 11, Área 116.",
        profesion: "Maestra en Escuela Nº 2 de Florencio Varela",
        historia: "CONADEP: 1368\nDomicilio: Intendente Oliveri 536, Quilmes.",
        imagen: ""
    },
    {
        lat: -34.7835, lng: -58.2590,
        nombre: "RINGA, Francisco (33 años)",
        apodo: "Sin datos",
        fecha: "29/10/1976",
        dni: "Sin datos",
        nacionalidad: "Italiano",
        lugar: "Los Cooperarios, Quilmes. Zona 1, Subzona 11, Área 116.",
        profesion: "Sin datos",
        historia: "CONADEP: 2124\nJuventud Peronista – Montoneros.",
        imagen: ""
    },
    {
        lat: -34.7980, lng: -58.2770,
        nombre: "RÍOS, Enrique Avelino",
        apodo: "Sin datos",
        fecha: "1978",
        dni: "Sin datos",
        nacionalidad: "Argentino",
        lugar: "Dock Sud. Zona 1, Subzona 11, Área 116.",
        profesion: "Obrero portuario",
        historia: "Domicilio: Guatemala y Antártida Argentina, Ingeniero Allan, Florencio Varela.\nMilitante del PRT-ERP.",
        imagen: ""
    },
    {
        lat: -34.7895, lng: -58.2650,
        nombre: "RODRÍGUEZ, Blanca Margarita (52 años)",
        apodo: "Sin datos",
        fecha: "16/05/1977",
        dni: "LE: 6.350.962",
        nacionalidad: "Uruguaya",
        lugar: "Valparaíso 1163 (o 960), Barrio Valentín Alsina, Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Empleada doméstica",
        historia: "SDH: 669\nPRT-ERP.",
        imagen: ""
    },
    {
        lat: -34.7845, lng: -58.2800,
        nombre: "RODRÍGUEZ CHAZARRETA, Elías Abel (20 años)",
        apodo: "NEGRO / CHAMA / CHAMACO / HUGO ARANA",
        fecha: "01/02/1977",
        dni: "12.589.351",
        nacionalidad: "Argentina",
        lugar: "Arrecifes y Quequén, Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Contratista de mantenimiento del Automóvil Club Argentino",
        historia: "SDH: 3543\nDomicilio: Inca 3004, Gregorio Laferrere, La Matanza.\nJuventud Peronista – Montoneros. Visto en CCD Pozo de Quilmes.",
        imagen: ""
    },
    {
        lat: -34.7960, lng: -58.2610,
        nombre: "ROLÓN ESCOBAR, Enrique (35 años)",
        apodo: "BARBA / BIGOTE",
        fecha: "18/02/1977",
        dni: "LE: 6.350.962",
        nacionalidad: "Argentino",
        lugar: "La Capilla, Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Ex empleado de Correos ENCoTel y ex obrero frigorífico",
        historia: "SDH: 3325\nJuventud Peronista – Montoneros. CCD: Escuela de Mecánica de la Armada.",
        imagen: ""
    },
    {
        lat: -34.7910, lng: -58.2740,
        nombre: "ROMERO MEZA, Alberto Ostiano (42 años)",
        apodo: "EL MAESTRO",
        fecha: "14/09/1977",
        dni: "LE: 5.154.082 / CI: 3.718.850",
        nacionalidad: "Argentina",
        lugar: "Nicaragua 239, Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Profesor (ACTV)",
        historia: "CONADEP: 1084\nVinculado a los Comandos Tecnológicos del Peronismo.",
        imagen: ""
    },
    {
        lat: -34.7870, lng: -58.2680,
        nombre: "SAPAG ROMEO, Ricardo Omar (24 años)",
        apodo: "VIRULANA / TATA",
        fecha: "30/06/1977",
        dni: "LE: 10.660.079",
        nacionalidad: "Argentina",
        lugar: "Ruta Provincial Nº 2 Km 31.000, Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Estudiante",
        historia: "REDEFA: 6700\nEjecución sumaria.\nJuventud Peronista – Montoneros.",
        imagen: ""
    },
    {
        lat: -34.7815, lng: -58.2635,
        nombre: "SCHAND DE IULA, Silvia Raquel (22 años)",
        apodo: "LA PETISA",
        fecha: "26/05/1978",
        dni: "Sin datos",
        nacionalidad: "Argentina",
        lugar: "Ramos Mejía. Zona 1, Subzona 11, Área 114.",
        profesion: "Partido Comunista Marxista-Leninista",
        historia: "CONADEP: 4119\nEmbarazada de tres meses.",
        imagen: ""
    },
    {
        lat: -34.7942, lng: -58.2575,
        nombre: "SOSA SEISDEDOS, Alberto Oscar (36 años)",
        apodo: "Sin datos",
        fecha: "13/05/1977",
        dni: "LE: 4.884.154",
        nacionalidad: "Argentina",
        lugar: "Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Obrero metalúrgico TAMET (delegado gremial), Santo Domingo y Peripipí, Pompeya, Capital Federal",
        historia: "SDH: 2601\nPartido Revolucionario de los Trabajadores – Ejército Revolucionario del Pueblo (PRT-ERP). CCD: Panamericana.",
        imagen: ""
    },
    {
        lat: -34.8015, lng: -58.2700,
        nombre: "SOUTO, Manuel Ramón (30 años)",
        apodo: "EL GALLEGO",
        fecha: "13/07/1976",
        dni: "5.769.751",
        nacionalidad: "Argentina",
        lugar: "Lomas de Zamora. Zona 1, Subzona 11, Área 116.",
        profesion: "Obrero de Peugeot",
        historia: "Partido Revolucionario de los Trabajadores – Ejército Revolucionario del Pueblo (PRT-ERP).",
        imagen: ""
    },
    {
        lat: -34.7825, lng: -58.2760,
        nombre: "SUÁREZ, Dominga (21 años)",
        apodo: "Sin datos",
        fecha: "05/1976",
        dni: "CI: 232125",
        nacionalidad: "Argentina",
        lugar: "Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Obrera textil, fábrica de pantalones (Once, Capital Federal)",
        historia: "CONADEP: 4405",
        imagen: ""
    },
    {
        lat: -34.7955, lng: -58.2855,
        nombre: "SUASNAVAR VEXENAT, Teresita María (23 años)",
        apodo: "Sin datos",
        fecha: "01/03/1977",
        dni: "10.929.469 / CI: 6.792.607",
        nacionalidad: "Argentina",
        lugar: "Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Sin datos",
        historia: "SDH: 1638\nMontoneros, grupo de Villa del Plata.",
        imagen: ""
    },
    {
        lat: -34.7785, lng: -58.2605,
        nombre: "TARANTO de ALTAMIRANDA, Rosa Luján (20 años)",
        apodo: "SUSANA GITANA",
        fecha: "13/05/1977",
        dni: "12.760.551",
        nacionalidad: "Argentina",
        lugar: "Perú y Padre Elía s/n°, Ingeniero Allan, Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Ama de casa",
        historia: "CONADEP: 7317\nEmbarazada de 7 meses (hija localizada y restituida).\nPartido Revolucionario de los Trabajadores – Ejército Revolucionario del Pueblo (PRT-ERP). CCD: El Vesubio.",
        imagen: ""
    },
    {
        lat: -34.7990, lng: -58.2665,
        nombre: "TOLOSA PENELA de REGGIARDO, María Rosa Ana (24 años)",
        apodo: "Sin datos",
        fecha: "08/02/1977",
        dni: "Sin datos",
        nacionalidad: "Argentina",
        lugar: "Monteagudo Nº 199, Florencio Varela. Zona 1, Subzona 11, Área 112.",
        profesion: "Estudiante de Arquitectura UNLP",
        historia: "CONADEP: 1835\nEmbarazada de 6 meses (hijos localizados – mellizos).\nJuventud Universitaria Peronista (JUP). CCD: La Cacha (Arana).",
        imagen: ""
    },
    {
        lat: -34.7805, lng: -58.2655,
        nombre: "VALANCI SAYA, Miguel Ángel (19 años)",
        apodo: "Sin datos",
        fecha: "19/07/1977",
        dni: "13.438.008",
        nacionalidad: "Argentino",
        lugar: "Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Sin datos",
        historia: "SDH: 2352\nPartido Revolucionario de los Trabajadores – Ejército Revolucionario del Pueblo (PRT-ERP).",
        imagen: ""
    },
    {
        lat: -34.7937, lng: -58.2785,
        nombre: "VÁZQUEZ, Marcos Augusto (23 años)",
        apodo: "Sin datos",
        fecha: "02/12/1976",
        dni: "CI: 5.633.232",
        nacionalidad: "Argentino",
        lugar: "Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Delegado gremial de Molinos Río de la Plata (grupo Bunge & Born). Integrante de la CGT-R",
        historia: "CONADEP: 2687\nMontoneros. Visto con vida en el CCD \"Garage Azopardo\".",
        imagen: ""
    },
    {
        lat: -34.7968, lng: -58.2625,
        nombre: "VELA ÁLZAGA UNZUÉ, César Miguel (26 años)",
        apodo: "EL FLACO ANÍBAL",
        fecha: "18/01/1977",
        dni: "LE: 8.442.782",
        nacionalidad: "Argentino",
        lugar: "Capital Federal. Zona 1, Subzona 11, Área 116.",
        profesion: "Sin datos",
        historia: "CONADEP: 2033\nMontoneros. CCD: Escuela de Mecánica de la Armada.",
        imagen: ""
    },
    {
        lat: -34.7888, lng: -58.2725,
        nombre: "VENTURA PASSERO, Víctor Hugo (26 años)",
        apodo: "Sin datos",
        fecha: "05/01/1977",
        dni: "LE: 8.436.574 / CI: 06.608.841",
        nacionalidad: "Argentino",
        lugar: "Alvarado Nº 344, Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Obrero de Mercedes Benz (delegado de \"Comisión de los 9\")",
        historia: "CONADEP: 4245\nCCD: Brigada de Investigaciones de Lanús.\nIntegrante del Frente Mecánico Eva Perón adherido a la JTP.",
        imagen: ""
    },
    {
        lat: -34.7948, lng: -58.2565,
        nombre: "VERA, Laura",
        apodo: "Sin datos",
        fecha: "01/05/1976",
        dni: "Sin datos",
        nacionalidad: "Argentina",
        lugar: "Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Sin datos",
        historia: "",
        imagen: ""
    },
    {
        lat: -34.7818, lng: -58.2795,
        nombre: "ZURITA, Sergio",
        apodo: "Sin datos",
        fecha: "01/02/1978",
        dni: "LE: 08.481.149",
        nacionalidad: "Argentino",
        lugar: "Calle 129 e/ 62 y 63, Berisso. Zona 1, Subzona 11, Área FT5.",
        profesion: "Sin datos",
        historia: "CONADEP: 4399\nCCD: Batallón de Infantería de Marina N°3 / La Cacha.\nPartido Comunista Marxista-Leninista.",
        imagen: ""
    },
    {
        lat: -34.7973, lng: -58.2755,
        nombre: "ZURITA, Alejo",
        apodo: "Sin datos",
        fecha: "26/05/1978",
        dni: "LE: 11.035.440",
        nacionalidad: "Argentino",
        lugar: "Vélez Sarsfield al 2100, Capital Federal. Zona 1, Subzona Capital Federal.",
        profesion: "Sin datos",
        historia: "CONADEP: 4400\nCCD: El Banco (trasladado en junio o julio de 1978).\nPartido Comunista Marxista-Leninista.",
        imagen: ""
    },
    {
        lat: -34.7852, lng: -58.2670,
        nombre: "ZURITA, Claudio",
        apodo: "Sin datos",
        fecha: "20/07/1979",
        dni: "11.419.918",
        nacionalidad: "Argentino",
        lugar: "Mar del Plata. Zona 1, Subzona 15.",
        profesion: "Sin datos",
        historia: "CONADEP: 4401\nPartido Comunista Marxista-Leninista.",
        imagen: ""
    },
];
