const datosMemoria = [
    {
        lat: -34.7965, lng: -58.2838,
        nombre: "ACOSTA SELFO, Ramón Gumersindo Manuel (34 años)",
        apodo: "Juan Carlos Gómez",
        fecha: "21/02/1976",
        dni: "5.939.386",
        nacionalidad:"Argentino",
        lugar: "El Cadillal, Tafí Viejo, Tucumán. Zona 3, Subzona 32, Área 321",
        profesion: "Obrero portuario, Delegado Gremial Ferrodúctil (Metalúrgico)",
        historia:"Partido Revolucionario de los Trabajadores-Ejército Revolucionario del Pueblo PRT-ERP",
        imagen: "images/ACOSTA-SELFO.png"
    },
    {
        lat: -34.7940, lng: -58.2800,
        nombre: "ACUÑA RAMOS MEJÍA, Federico Matías Ramón (26 años)",
        apodo: "Damián Barrios",
        fecha: "00/03/1977",
        dni: "8.474.425",
        nacionalidad:"Argentino",
        lugar: "Capital Federal. Zona 1, Subzona Capital Federal, Área 1. Operativo en una fábrica. Militaba en Florencio Varela.",
        profesion: "Sin datos",
        historia:"CCD:EL BANCO / PUENTE 12\nOperativo en una fábrica. Sobrino de José Alfredo Martínez de Hoz. Militaba en Florencio Varela",
        imagen: "images/ACUÑA-RAMOS-MEJÍA.png"
    },
    {
        lat: -34.7910, lng: -58.2770,
        nombre: "ACUÑA, Néstor Porfirio (27 años)",
        apodo: "Falucho",
        fecha: "25/01/1978",
        dni: "Sin datos",
        nacionalidad:"Sin datos",
        lugar: "Plaza Constitución. Zona 1, Subzona Capital Federal.",
        profesion: "Obrero textil. Partido Comunista Marxista-Leninista.",
        ccd: "El Banco",
        historia: "Domicilio: López Escribano 1114, Florencio Varela\n CCD:EL BANCO\nPartido Comunista Marxista-Leninista",
        imagen: ""
    },
    {
        lat: -34.7550, lng: -58.2100,
        nombre: "ACUÑA BRIZUELA, Teodosio (21 años)",
        apodo: "Gordo Hugo / Toto",
        fecha: "15/04/1976",
        dni: "Sin datos",
        nacionalidad:"Argentino",
        lugar: "Ramos Mejía. Zona 1, Subzona 11, Área 116",
        profesion: "Obrero frigorífico Subpga",
        ccd: "El Banco",
        historia: "CCD: EL BANCO\nPartido Comunista Marxista-Leninista\nEs detenido en una pensión de Ramos Mejía y en su Legajo SDH figura que fue detenido entre el trayecto de su trabajo (Camino General Belgrano Km. 21.500. Berazategui) a su casa",
        imagen: ""
    },
    {
        lat: -34.8020, lng: -58.2750,
        nombre: "ALBORNOZ GARCÍA, Mario Raúl (24 años)",
        apodo: "Sin datos",
        fecha: "25/07/1975 (Ejecución Sumaria)",
        dni: "8.575.579",
        nacionalidad:"Argentino",
        lugar: "Monseñor Aragón entre Estados Unidos y Agrelo, Barrio La Pileta, Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Sin datos",
        historia: "Partido Revolucionario de los Trabajadores-Ejército Revolucionario del Pueblo PRT-ERP",
        imagen: ""
    },
    {
        lat: -34.7780, lng: -58.2580,
        nombre: "ALTAMIRANDA ROJAS, Horacio Antonio (22 años)",
        apodo: "Gallego Marcelo / Roberto",
        fecha: "13/05/1977",
        dni: "11.886.638",
        nacionalidad:"Argentino",
        lugar: "Perú y P. Elía s/n, Ingeniero Allan, Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Delegado gremial de Rigolleau",
        historia: "CCD: EL VESUBIO\nPartido Revolucionario de los Trabajadores-Ejército Revolucionario del Pueblo PRT-ERP",
        imagen: "images/ALTAMIRANDA-ROJAS.png"
    },
    {
        lat: -34.7950, lng: -58.2820,
        nombre: "ARDETI MOLARO, Enrique Néstor (44 años)",
        apodo: "Gordo Ramón",
        fecha: "06/08/1979",
        dni: "6.222.896",
        nacionalidad:"Argentino",
        lugar: "Avenida Vázquez 375, Florencio Varela, a las 17:20 horas. Zona 1, Subzona 11, Área 116.",
        profesion: "Sin datos",
        historia: "Domicilio: Calle 46 Nº 1827, La Plata.\nNro. de legajo: 2516\nFuerzas Armadas Peronistas FAP- Peronismo de Base PB\nCCD: ESCUELA DE MECANICA DE LA ARMADA",
        imagen: "images/ARDETI-MOLARO.png"
    },
    {
        lat: -34.7680, lng: -58.2350,
        nombre: "ASCONAPE LUAYZA, María Cristina (24 años)",
        apodo: "Sin datos",
        fecha: "12/09/1975 (Ejecución Sumaria)",
        dni: "6.553.297",
        nacionalidad:"Argentina",
        lugar: "Alelíes esquina Las Orquídeas, Bosques, Ruta 2 Km 28.800, Florencio Varela. Zona 1, Subzona 11, Área 116.",
        profesion: "Ayudante de radiología. PRT-ERP.",
        historia: "Partido Revolucionario de los Trabajadores-Ejército Revolucionario del Pueblo PRT-ERP",
        imagen: "images/ASCONAPE-LUAYZA.png"
    },
    {
        lat: -34.7990, lng: -58.2870,
        nombre: "BARBEITO RODRÍGUEZ, María Cristina (22 años)",
        apodo: "Sin datos",
        fecha: "17/10/1977 (Asesinada)",
        dni: "11.741.547",
        nacionalidad:"Argentina",
        lugar: "Chubut y Jujuy, Florencio Varela. Zona 1, Subzona 11, Área 116. Compañera de Juan Carlos Follonier. Es asesinada en Varela poniendo a reparo su hijo y cubriendo a Víctor Hugo Díaz.",
        profesion: "Estudiante",
        historia: "REDEFA 116\nMontoneros. Compañera de Juan Carlos Follonier. Es asesinada en Varela poniendo a reparo su hijo y cubriendo a Víctor Hugo Díaz",
        imagen: "images/BARBEITO-RODRÍGUEZ.png"
    },
    {
        lat: -34.7900, lng: -58.2760,
        nombre: "BARTUCCI DEMASI, Francisco (29 años)",
        apodo: "Pancho",
        fecha: "29/07/1976",
        dni: "CI: 9.744.456",
        nacionalidad:"Italiano",
        lugar: "Curva de Berraymundo, Florencio Varela, a las 17 horas. Zona 1, Subzona 11, Área 116.",
        profesion: "Obrero de SEGBA.",
        historia: "Domicilio: Luis Villar 664, Florencio Varela.\nNro. de legajo: 4329\nMontoneros",
        imagen: "images/BARTUCCI-DEMASI.png"
    }
];
